spring.application.name=sistema-delivery
<<<<<<< HEAD

spring.datasource.url=jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_HIST
spring.jpa.properties.org.hibernate.envers.revision_field_name=REV
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=REV_TYPE
=======
>>>>>>> 7b319e19d542f5496d63ac9a598d3699905b5194
